### ISSUE TITLE
SimpleDateFormat not designed for multithread uses

### ISSUE THREAD

**Issue by yev** [jlewallen/git-teamcity#2]
Hi guys,
Just a little note.
I noticed that you are using SimpleDateFormat in your Constants.java may cause some problems in multithread env.

It would be more reliable to create a new instance of SimpleDateFormat  or synchronize the instance.

public static final SimpleDateFormat VERSION_DATE = new SimpleDateFormat(Constants.VERSION_DATE_FORMAT, Locale.US);

**Comment by jlewallen** [comment]
Thanks for the heads up... I'm not the original author of most of this and the plugin itself is deprecated as Git support's built in now. I should nuke this repository...
